Description: Notify Cause of Error
Resources:
  COEQueue:
    Type: "AWS::SQS::Queue"
  COETopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        -
          Endpoint: !GetAtt COEQueue.Arn
          Protocol: "sqs"
  COEQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
        - Sid: AllowFromCOETopic
          Effect: Allow
          Principal: "*"
          Action:
            - sqs:SendMessage
          Resource: "*"
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref COETopic
      Queues:
        - !Ref COEQueue
Outputs:
  COETopicOut:
    Description: Cause Of Error topic name
    Value: !Ref COETopic
    Export:
      Name: coe-topic
