Description: Log AWS API calls for auditing
Resources:
  AuditBucket:
    Type: "AWS::S3::Bucket"
  AuditBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref AuditBucket
      PolicyDocument:
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudtrail.amazonaws.com"
            Action:
              - "s3:GetBucketAcl"
            Resource: !GetAtt AuditBucket.Arn
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudtrail.amazonaws.com"
            Action:
              - "s3:PutObject"
            Resource: !Join [ "", [!GetAtt AuditBucket.Arn,"/AWSLogs/", !Ref "AWS::AccountId" ,"/*"]]
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
  AuditGroup:
    Type: "AWS::Logs::LogGroup"
  AuditRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudtrail.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "logs:CreateLogStream"
                Resource:
                  - !Sub ${AuditGroup.Arn}
              -
                Effect: "Allow"
                Action: "logs:PutLogEvents"
                Resource:
                  - !Sub ${AuditGroup.Arn}
  AuditTrail:
    DependsOn:
        - AuditBucketPolicy
    Type: "AWS::CloudTrail::Trail"
    Properties:
      CloudWatchLogsLogGroupArn: !GetAtt AuditGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt AuditRole.Arn
      S3BucketName: !Ref AuditBucket
      IsLogging: true
Outputs:
  AuditGroupOut:
    Description: Log group for trail logs
    Value: !Ref AuditGroup
    Export:
      Name: audit-loggroup
